### ISSUE TITLE
Url available as an environment variable

### ISSUE THREAD

**Issue by dejanvasic85** [technicallyjosh/pino-http-send#2]
Would like to send the logs to different URL's based on environment variable. 
E.g. `PINO_HTTP_SEND_URL` rather than having to pass it in as an argument.

**Comment by technicallyjosh** [comment]
Actually you can. That's what I use instead of a flag. 

See https://github.com/technicallyjosh/pino-http-send#environment-variables.

Are you somehow getting something different or having an issue? If you can provide details if you are running into something that would be helpful.

**Comment by dejanvasic85** [comment]
Yeah, it would be great if I don't have to supply the URL as an argument. So this is what I'm trying to do:

```
PINO_HTTP_SEND_URL=http://sumologic... ts-node app.ts | pino-http-send 
```

But I'm getting the `url is a required parameter`. Probably because of this? https://github.com/technicallyjosh/pino-http-send/blob/master/src/args.ts#L35 

Thanks @technicallyjosh

**Comment by technicallyjosh** [comment]
The required just means it needs to be defined "somewhere" e.g. flag or env var. This could be an issue with how ts-node loads env. Have you tried this with plain node?

**Comment by technicallyjosh** [comment]
So it seems like you are running into a basic sub process issue. See [here](https://unix.stackexchange.com/questions/134735/environment-variables-are-not-set-when-my-function-is-called-in-a-pipeline) for an explanation on what a piped process really is and what's happening.

When you just run `PINO_HTTP_SEND_URL=http://someroute ts-node app.ts | pino-http-send`, the environment variable is not picked up by the piped process...

Generally you'd install this to local modules and _not global_ and utilize there within the context of package.json scripts.

I'd suggest doing the following:

1. Install locally `npm i pino-http-send`
2. Make a start script of some kind in your package.json e.g. `"start": "ts-node app.ts | pino-http-send"`
3. Then you can run something like `PINO_HTTP_SEND_URL=http://myurl npm start`

**Comment by dejanvasic85** [comment]
Yeah. That worked. Thanks!
