### ISSUE TITLE
[feature request] Usage as a module

### ISSUE THREAD

**Issue by DRoet** [technicallyjosh/pino-http-send#5]
I don't think this is currently supported, but it would be neat if we could use this library programmatically as a module.

The [LogFlare module](https://github.com/Logflare/pino-logflare) might be a good starting point on how to do this, but essentially you would want something like:

```js
import { createWriteStream } from 'pino-http-send'

// create stream w/ options
const stream = createWriteStream({
    url: "https://example.com/logging"
});

// create pino loggger
const logger = pino({
    level: 'info
}, stream);
```

**Comment by technicallyjosh** [comment]
That's a good idea. I'm always open to PRs. If not, I can probably get to this this weekend actually.

**Comment by technicallyjosh** [comment]
I have the API worked out locally on a branch and initial testing works. Should have a new version shortly.

**Comment by DRoet** [comment]
@technicallyjosh awesome, much appreciated!

**Comment by technicallyjosh** [comment]
v0.4.0 adds this feature. See the docs for usage. Thanks for the feature idea! 🎉

**Comment by DRoet** [comment]
Thanks for the quick response! one last thing:

Would it make sense to change the entrypoints in package.json?

`bin` -> cli entrypoint (index.ts)
`main` -> module/api entrypoint (stream.ts)

So you can do `import { createWriteStream } from 'pino-http-send'` instead of `'pino-http-send/dist/stream'`?

This shouldn't affect the CLI usage

**Comment by dotjoshrc** [comment]
v0.4.2 has the API exports as default now
